// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Dbca4Q-noLZqGYO6gcLMN-yb7HonT90',
    appId: '1:641933931474:web:1f4f5f662178eacc3f8e0b',
    messagingSenderId: '641933931474',
    projectId: 'doctorpoint-245df',
    authDomain: 'doctorpoint-245df.firebaseapp.com',
    storageBucket: 'doctorpoint-245df.firebasestorage.app',
    measurementId: 'G-LBMRJZDQY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf7WsSZrjEHiXTOm_5fYC_CBhL_yb-ojY',
    appId: '1:641933931474:android:c44159cc9c0c9ecc3f8e0b',
    messagingSenderId: '641933931474',
    projectId: 'doctorpoint-245df',
    storageBucket: 'doctorpoint-245df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYy17ODyvQxds5tuMOUxusP03foH3b_pU',
    appId: '1:641933931474:ios:cf6b1e3b0822c70f3f8e0b',
    messagingSenderId: '641933931474',
    projectId: 'doctorpoint-245df',
    storageBucket: 'doctorpoint-245df.firebasestorage.app',
    iosClientId: '641933931474-v7ipb9ptuq55hfc4d0lu5aroua2nvbn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorpointApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYy17ODyvQxds5tuMOUxusP03foH3b_pU',
    appId: '1:641933931474:ios:cf6b1e3b0822c70f3f8e0b',
    messagingSenderId: '641933931474',
    projectId: 'doctorpoint-245df',
    storageBucket: 'doctorpoint-245df.firebasestorage.app',
    iosClientId: '641933931474-v7ipb9ptuq55hfc4d0lu5aroua2nvbn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorpointApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Dbca4Q-noLZqGYO6gcLMN-yb7HonT90',
    appId: '1:641933931474:web:f5502e4bb7cd457b3f8e0b',
    messagingSenderId: '641933931474',
    projectId: 'doctorpoint-245df',
    authDomain: 'doctorpoint-245df.firebaseapp.com',
    storageBucket: 'doctorpoint-245df.firebasestorage.app',
    measurementId: 'G-SY7FJDJBF3',
  );
}
